In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("/content/drive/MyDrive/yelp_dataset/final_data_yelp")

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
df

        Unnamed: 0             business_id      city  ...     fips    cases  deaths
0                0  uexKxrLmPO5iaXRT9TvWqQ  Portland  ...      0.0      0.0     0.0
1                1  b4PgITSqSWoPhyJ-Mjko7Q  Portland  ...      0.0      0.0     0.0
2                2  2EJpVjliJ6Ceijbz9HSpeQ  Portland  ...      0.0      0.0     0.0
3                3  7m_Tj6xC5CjulQ-6Wucdpw  Portland  ...      0.0      0.0     0.0
4                4  DgvT9AiuePR8Z0SKV5BFvw  Portland  ...      0.0      0.0     0.0
...            ...                     ...       ...  ...      ...      ...     ...
197944      197944  BO4Usu_YSE7jlmchGMeVcw    Boston  ...  25025.0  70398.0  1548.0
197945      197945  -WG2sv6ApNh1fa7ot-QAEA    Boston  ...  25025.0  70398.0  1548.0
197946      197946  EbUZhM4fLpsWQ8fpBhhgEQ    Boston  ...  25025.0  70398.0  1548.0
197947      197947  IqyqfQFnBsOIReGrcgaYhA    Boston  ...  25025.0  70398.0  1548.0
197948      197948  DZm67Anqn1IQTB9iGvw4Fw    Boston  ...  25025.0  70398.0  1548.0

[197949 rows x 20 columns]

In [10]:
for i in range(len(df)):
    if df.loc[i,'Vader Sentiment'] >0 :
        df.loc[i,'label'] = 1
    else:
        df.loc[i,'label'] = 0

KeyboardInterrupt: ignored

In [ ]:
(df['label']== 0).sum() #total number of 1 in the column

In [ ]:
df.columns

In [ ]:
df.to_csv("/content/drive/MyDrive/yelp_dataset/final_data_yelp2.csv")

In [11]:
df_service = df.text.str.count("staff|wait|shutdown|delivery|online ordering|accommodating|help|greeted|UberEats")

In [12]:
df_service

0         1
1         0
2         0
3         0
4         0
         ..
197944    1
197945    0
197946    0
197947    0
197948    0
Name: text, Length: 197949, dtype: int64

In [13]:
df['service'] = df.text.str.count("staff|wait|shutdown|delivery|online ordering|accommodating|help|greeted|UberEats")

In [14]:
df

        Unnamed: 0             business_id      city  ...  deaths label  service
0                0  uexKxrLmPO5iaXRT9TvWqQ  Portland  ...     0.0   1.0        1
1                1  b4PgITSqSWoPhyJ-Mjko7Q  Portland  ...     0.0   1.0        0
2                2  2EJpVjliJ6Ceijbz9HSpeQ  Portland  ...     0.0   1.0        0
3                3  7m_Tj6xC5CjulQ-6Wucdpw  Portland  ...     0.0   1.0        0
4                4  DgvT9AiuePR8Z0SKV5BFvw  Portland  ...     0.0   1.0        0
...            ...                     ...       ...  ...     ...   ...      ...
197944      197944  BO4Usu_YSE7jlmchGMeVcw    Boston  ...  1548.0   NaN        1
197945      197945  -WG2sv6ApNh1fa7ot-QAEA    Boston  ...  1548.0   NaN        0
197946      197946  EbUZhM4fLpsWQ8fpBhhgEQ    Boston  ...  1548.0   NaN        0
197947      197947  IqyqfQFnBsOIReGrcgaYhA    Boston  ...  1548.0   NaN        0
197948      197948  DZm67Anqn1IQTB9iGvw4Fw    Boston  ...  1548.0   NaN        0

[197949 rows x 22 columns]

In [15]:
df.loc[0,'text']

'Yes I am a fan    of the food  Ive tried more than a few Chinese American restaurants in Portland and the bay area over the years and the food here is very tasty especially if you eat there  Heres the downside to a great flavorful meal the staffcustomer service rate 1 star  My first visit a few days before todays trip was to check it out  That was good eating but another tables bill was charged to my card by mistake  It was immediately corrected There were 2 tables one with 2 people me at another and a guy at the bar not a full house by any means No need to make that kind of mistake  Not rude service just sloppy and inattentive  Today with only 3 customers 1 on the machines and 2 of us eating  at 215 pm on a Monday  I purchased several items expecting a bill of around 5000  It ended up being over 8000 because I had been charged the dinner prices instead of the lunch prices  You tell me is 215 closer to lunch or to dinner This was not communicated  If this had been in a full place maybe but this was just lack of communication and sloppy  I wasnt even handed a menu and had to get one myself after I questioned the bill  Yes I paid and I enjoyed taking it to our party later that night and yes Ill go back but Ill double check everything from start to finish'

In [16]:
(df['service']== 2).sum()

13358

In [17]:
df['food'] = df.text.str.count("delicious|tasty|flavors|tender|options|sauce|menu|drink|fusion|appetizers")

In [18]:
df

        Unnamed: 0             business_id      city  ... label service  food
0                0  uexKxrLmPO5iaXRT9TvWqQ  Portland  ...   1.0       1     2
1                1  b4PgITSqSWoPhyJ-Mjko7Q  Portland  ...   1.0       0     0
2                2  2EJpVjliJ6Ceijbz9HSpeQ  Portland  ...   1.0       0     1
3                3  7m_Tj6xC5CjulQ-6Wucdpw  Portland  ...   1.0       0     0
4                4  DgvT9AiuePR8Z0SKV5BFvw  Portland  ...   1.0       0     0
...            ...                     ...       ...  ...   ...     ...   ...
197944      197944  BO4Usu_YSE7jlmchGMeVcw    Boston  ...   NaN       1     0
197945      197945  -WG2sv6ApNh1fa7ot-QAEA    Boston  ...   NaN       0     0
197946      197946  EbUZhM4fLpsWQ8fpBhhgEQ    Boston  ...   NaN       0     0
197947      197947  IqyqfQFnBsOIReGrcgaYhA    Boston  ...   NaN       0     0
197948      197948  DZm67Anqn1IQTB9iGvw4Fw    Boston  ...   NaN       0     1

[197949 rows x 23 columns]

In [19]:
df['place'] = df.text.str.count("street|station|close|parking|near|outside seating|location|convenience|easy|find")

In [20]:
df['experience'] = df.text.str.count("Value|disappoint|recommend|accepted|charge|atmosphere|clean|amazing|expectation|hygiene practices")

In [21]:
df['hygiene'] = df.text.str.count("preacautions|precaution|precautionary|mask|masks|masked|gloves|glove|health|healthy|hygiene|hygienic|safety|isolation|isolate|sanitise|sanitisation|sanitize|sanitization|sanitiser|sanitizer|contact|contacts|contactless|virtual|oximeter|temperature|thermometer|protocols|protocol|social distancing|social distance|clean|cleanliness|pure|germ free|sanitary|neater|neat|neatness")

In [22]:
df

        Unnamed: 0             business_id  ... experience hygiene
0                0  uexKxrLmPO5iaXRT9TvWqQ  ...          2       0
1                1  b4PgITSqSWoPhyJ-Mjko7Q  ...          0       0
2                2  2EJpVjliJ6Ceijbz9HSpeQ  ...          1       0
3                3  7m_Tj6xC5CjulQ-6Wucdpw  ...          0       0
4                4  DgvT9AiuePR8Z0SKV5BFvw  ...          2       0
...            ...                     ...  ...        ...     ...
197944      197944  BO4Usu_YSE7jlmchGMeVcw  ...          2       0
197945      197945  -WG2sv6ApNh1fa7ot-QAEA  ...          1       0
197946      197946  EbUZhM4fLpsWQ8fpBhhgEQ  ...          2       0
197947      197947  IqyqfQFnBsOIReGrcgaYhA  ...          0       0
197948      197948  DZm67Anqn1IQTB9iGvw4Fw  ...          1       0

[197949 rows x 26 columns]

In [25]:
(df['hygiene']== 4).sum()

217

In [26]:
df["service_per"] = df["service"] / df["review_word_count"] * 100

In [27]:
df

        Unnamed: 0             business_id  ... hygiene service_per
0                0  uexKxrLmPO5iaXRT9TvWqQ  ...       0    0.398406
1                1  b4PgITSqSWoPhyJ-Mjko7Q  ...       0    0.000000
2                2  2EJpVjliJ6Ceijbz9HSpeQ  ...       0    0.000000
3                3  7m_Tj6xC5CjulQ-6Wucdpw  ...       0    0.000000
4                4  DgvT9AiuePR8Z0SKV5BFvw  ...       0    0.000000
...            ...                     ...  ...     ...         ...
197944      197944  BO4Usu_YSE7jlmchGMeVcw  ...       0    2.222222
197945      197945  -WG2sv6ApNh1fa7ot-QAEA  ...       0    0.000000
197946      197946  EbUZhM4fLpsWQ8fpBhhgEQ  ...       0    0.000000
197947      197947  IqyqfQFnBsOIReGrcgaYhA  ...       0    0.000000
197948      197948  DZm67Anqn1IQTB9iGvw4Fw  ...       0    0.000000

[197949 rows x 27 columns]

In [28]:
df["food_per"] = df["food"] / df["review_word_count"] * 100

In [29]:
df["place_per"] = df["place"] / df["review_word_count"] * 100

In [30]:
df["experience_per"] = df["experience"] / df["review_word_count"] * 100

In [31]:
df["hygiene_per"] = df["hygiene"] / df["review_word_count"] * 100

In [32]:
df

        Unnamed: 0             business_id  ... experience_per hygiene_per
0                0  uexKxrLmPO5iaXRT9TvWqQ  ...       0.796813         0.0
1                1  b4PgITSqSWoPhyJ-Mjko7Q  ...       0.000000         0.0
2                2  2EJpVjliJ6Ceijbz9HSpeQ  ...       1.351351         0.0
3                3  7m_Tj6xC5CjulQ-6Wucdpw  ...       0.000000         0.0
4                4  DgvT9AiuePR8Z0SKV5BFvw  ...       5.128205         0.0
...            ...                     ...  ...            ...         ...
197944      197944  BO4Usu_YSE7jlmchGMeVcw  ...       4.444444         0.0
197945      197945  -WG2sv6ApNh1fa7ot-QAEA  ...       3.703704         0.0
197946      197946  EbUZhM4fLpsWQ8fpBhhgEQ  ...       4.761905         0.0
197947      197947  IqyqfQFnBsOIReGrcgaYhA  ...       0.000000         0.0
197948      197948  DZm67Anqn1IQTB9iGvw4Fw  ...       2.325581         0.0

[197949 rows x 31 columns]

In [33]:
df.to_csv("/content/drive/MyDrive/YELP/yelp_features_percentage.csv")